/**
 * Forensic Investigation Ontology — the complete cognitive map of a senior analyst.
 * Each node represents an artifact category the investigation MUST visit.
 * Rich directives tell ANY LLM exactly what to do, what evil looks like, and what to conclude.
 */

export interface InvestigationNode {
  readonly id: string;
  readonly category: string;
  readonly subcategory: string;
  readonly tool: string;
  readonly operation: string;
  readonly params?: Record<string, string>;
  readonly rationale: string;
  readonly whatEvilLooksLike: string;
  readonly whatNormalLooksLike: string;
  readonly hypothesisTested: string;
  readonly confirmationCriteria: string;
  readonly ifConfirmed: string;
  readonly ifAbsent: string;
  readonly evidenceType: readonly ("disk-windows" | "disk-linux" | "memory" | "pcap")[];
  readonly priority: number; // lower = higher priority
}

// The ontology: every node a senior FOR508 analyst checks, in methodological order.
export const INVESTIGATION_ONTOLOGY: readonly InvestigationNode[] = [
  // ─── FILESYSTEM TRIAGE ───
  { id: "fs_root", category: "FILESYSTEM", subcategory: "Root_Structure", tool: "filesystem", operation: "list_directory", params: { path: "/" }, rationale: "Initial triage: identify OS version, user accounts, suspicious root-level dirs", whatEvilLooksLike: "Directories like Quarantine, staging, PerfLogs with executables, unusual root folders not part of standard Windows", whatNormalLooksLike: "Standard Windows dirs: Users, Windows, Program Files, ProgramData, $Recycle.Bin", hypothesisTested: "Is this a standard Windows installation or has it been modified?", confirmationCriteria: "Non-standard directories at root level", ifConfirmed: "Investigate each anomalous directory for attacker staging", ifAbsent: "Proceed to user enumeration", evidenceType: ["disk-windows", "disk-linux"], priority: 1 },
  { id: "fs_users", category: "FILESYSTEM", subcategory: "User_Enumeration", tool: "filesystem", operation: "list_directory", params: { path: "/Users" }, rationale: "Identify all user accounts including admin, service, and deleted accounts", whatEvilLooksLike: "Multiple admin accounts (suffix -a), deleted service accounts, accounts created at suspicious times", whatNormalLooksLike: "1-3 user profiles + Default + Public", hypothesisTested: "Were additional accounts created for persistence?", confirmationCriteria: "Admin accounts or deleted service accounts that don't match org's naming convention", ifConfirmed: "Register T1136.001 finding, check account creation times in SAM", ifAbsent: "Standard user configuration — proceed to ProgramData", evidenceType: ["disk-windows"], priority: 2 },
  { id: "fs_programdata", category: "FILESYSTEM", subcategory: "ProgramData_Staging", tool: "filesystem", operation: "list_directory", params: { path: "/ProgramData" }, rationale: "ProgramData is #1 malware staging location — hidden by default, writable by all users", whatEvilLooksLike: "Directories mimicking Windows services (svchost, taskhost, winlogon-style names), random-named dirs with executables", whatNormalLooksLike: "Microsoft, Package Cache, regid, known app names (Adobe, Mozilla)", hypothesisTested: "Has malware been staged in ProgramData?", confirmationCriteria: "Directories containing .exe/.dll not matching known legitimate software", ifConfirmed: "Register T1036.005 masquerading finding, get file metadata for timestomping check", ifAbsent: "Check Program Files for installed hacking tools", evidenceType: ["disk-windows"], priority: 3 },
  { id: "fs_prefetch", category: "FILESYSTEM", subcategory: "Prefetch_Listing", tool: "filesystem", operation: "list_directory", params: { path: "/Windows/Prefetch" }, rationale: "Prefetch files prove program execution — each .pf file = one executed program", whatEvilLooksLike: "PSEXEC, MIMIKATZ, PROCDUMP, SDELETE, CERTUTIL, BITSADMIN, POWERSHELL with unusual hashes, tools known for LOLBin abuse", whatNormalLooksLike: "Standard Windows executables: SVCHOST, EXPLORER, CHROME, OUTLOOK, MSOFFICE apps", hypothesisTested: "Were hacking/lateral-movement tools executed on this host?", confirmationCriteria: "Prefetch files for known attack tools (sdelete, psexec, mimikatz, procdump, rubeus)", ifConfirmed: "Register T1059 execution finding, parse prefetch for timestamps and loaded DLLs", ifAbsent: "Execution evidence is absent — either no tools ran or prefetch was cleared (check if directory is unusually empty)", evidenceType: ["disk-windows"], priority: 4 },
  // ─── PERSISTENCE ───
  { id: "persist_registry", category: "PERSISTENCE", subcategory: "Registry_RunKeys", tool: "registry", operation: "get_persistence_keys", rationale: "Registry Run/RunOnce keys are the #1 persistence mechanism — checked first", whatEvilLooksLike: "Entries pointing to ProgramData, AppData\\Local\\Temp, randomized filenames, encoded PowerShell, unsigned binaries", whatNormalLooksLike: "Chrome Update, Windows Defender, Office updaters, Dell/Intel OEM tools", hypothesisTested: "Did the attacker establish registry-based persistence?", confirmationCriteria: "Run key value pointing to a path where we found suspicious executables", ifConfirmed: "Register T1547.001 finding with the specific key path and binary", ifAbsent: "Persistence not via Run keys — check scheduled tasks", evidenceType: ["disk-windows"], priority: 5 },
  { id: "persist_tasks", category: "PERSISTENCE", subcategory: "Scheduled_Tasks", tool: "persistence", operation: "check_scheduled_tasks", rationale: "Scheduled tasks provide persistence surviving reboot + lateral movement", whatEvilLooksLike: "Tasks running binaries from ProgramData/Temp, tasks created by non-admin, XML task files with encoded commands", whatNormalLooksLike: "Microsoft\\Windows\\* tasks, Google Update, Adobe Acrobat Update", hypothesisTested: "Did the attacker create scheduled tasks for persistence?", confirmationCriteria: "Task pointing to suspicious binary path or created in the attack timeframe", ifConfirmed: "Register T1053.005 finding", ifAbsent: "No task-based persistence — check services", evidenceType: ["disk-windows"], priority: 6 },
  { id: "persist_services", category: "PERSISTENCE", subcategory: "Service_Installation", tool: "persistence", operation: "check_services", rationale: "Services run as SYSTEM — highest privilege persistence", whatEvilLooksLike: "Services with ImagePath in Temp/ProgramData, random service names, services created in attack timeframe", whatNormalLooksLike: "Windows services, McAfee, Sysmon, VPN clients", hypothesisTested: "Did the attacker install a malicious service?", confirmationCriteria: "Service ImagePath matches suspicious binary location from earlier findings", ifConfirmed: "Register T1543.003 finding", ifAbsent: "No service persistence — check startup locations", evidenceType: ["disk-windows"], priority: 7 },
  { id: "persist_startup", category: "PERSISTENCE", subcategory: "Startup_Folders", tool: "persistence", operation: "check_startup_locations", rationale: "50+ startup locations beyond Run keys (Startup folder, Winlogon, AppInit_DLLs, etc.)", whatEvilLooksLike: "LNK files to suspicious binaries, DLLs in AppInit, Shell extensions pointing to attacker tools", whatNormalLooksLike: "Standard Windows startup, office shortcuts", hypothesisTested: "Is there persistence via lesser-known autostart locations?", confirmationCriteria: "Any autostart entry referencing paths from earlier findings", ifConfirmed: "Register finding with specific vector", ifAbsent: "Standard persistence vectors clear — check WMI", evidenceType: ["disk-windows"], priority: 8 },
  // ─── EXECUTION ARTIFACTS ───
  { id: "exec_amcache", category: "EXECUTION", subcategory: "Amcache_History", tool: "execution_artifacts", operation: "parse_amcache", rationale: "Amcache records SHA1 hash + path + install time for EVERY executed binary — survives deletion", whatEvilLooksLike: "Entries for executables from ProgramData/Temp with recent install times matching attack window", whatNormalLooksLike: "Windows Update binaries, installed apps", hypothesisTested: "Can we get the SHA1 hash of the malware for IOC lookup?", confirmationCriteria: "Amcache entry for any binary found in suspicious directories (ProgramData staging, AppData temps)", ifConfirmed: "Register finding with hash — enables VirusTotal lookup and attribution", ifAbsent: "Amcache may have been cleared or binary never registered", evidenceType: ["disk-windows"], priority: 9 },
  { id: "exec_shimcache", category: "EXECUTION", subcategory: "Shimcache_AppCompat", tool: "execution_artifacts", operation: "parse_shimcache", rationale: "Shimcache tracks binary presence on disk (not always execution) — survives clearing", whatEvilLooksLike: "Entries for suspicious binaries with timestamps in attack window", whatNormalLooksLike: "System DLLs, installed applications", hypothesisTested: "Were attack tools present on disk during the intrusion window?", confirmationCriteria: "Shimcache entry for known-malicious binary paths", ifConfirmed: "Corroborates timeline of attack", ifAbsent: "Binary may pre-date shimcache coverage window", evidenceType: ["disk-windows"], priority: 10 },
  // ─── EVENT LOGS ───
  { id: "evtx_security", category: "EVENT_LOGS", subcategory: "Security_Log", tool: "event_logs", operation: "parse_event_log", params: { path: "/Windows/System32/winevt/Logs/Security.evtx" }, rationale: "Security.evtx contains logon events (4624/4625), privilege use, account management — the backbone of any investigation", whatEvilLooksLike: "Type 3/10 logons from unusual IPs, 4672 special privileges to non-admin accounts, 4720/4722 new accounts", whatNormalLooksLike: "Regular user logons, scheduled task logons (Type 5), machine account auth", hypothesisTested: "Is there evidence of unauthorized logon or privilege escalation?", confirmationCriteria: "Type 10 RDP or Type 3 network logon from an IP not in the organization's range, OR total absence of the log (indicates clearing)", ifConfirmed: "Register T1078 (valid accounts) or T1070.001 (log clearing) finding", ifAbsent: "Log is missing or empty — this IS a finding (T1070.001 Indicator Removal)", evidenceType: ["disk-windows"], priority: 11 },
  { id: "evtx_logon_corr", category: "EVENT_LOGS", subcategory: "Logon_Session_Correlation", tool: "event_logs", operation: "correlate_logon_events", rationale: "Match logon (4624) with logoff (4634) to identify session durations and anomalous access patterns", whatEvilLooksLike: "Short sessions at off-hours, sessions from multiple IPs for same account simultaneously, sessions without matching logoff (killed)", whatNormalLooksLike: "Business-hour sessions, consistent source IPs per user", hypothesisTested: "Were there anomalous authentication sessions?", confirmationCriteria: "Sessions from the attacker's IP or at times correlating with other attack evidence", ifConfirmed: "Register T1078 finding with session details", ifAbsent: "No anomalous sessions detected", evidenceType: ["disk-windows"], priority: 12 },
  // ─── ANTI-FORENSICS ───
  { id: "af_timestomp", category: "ANTI_FORENSICS", subcategory: "Timestomping_Detection", tool: "anti_forensics", operation: "detect_timestomping", rationale: "$SI timestamps are trivially modified; $FN timestamps require raw MFT write — comparing them detects timestomping", whatEvilLooksLike: "$SI.Created BEFORE $FN.Created (impossible without manipulation), all 4 $SI timestamps identical", whatNormalLooksLike: "$SI.Created >= $FN.Created, timestamps within logical range", hypothesisTested: "Did the attacker backdate files to avoid timeline analysis?", confirmationCriteria: "$SI.Created < $FN.Created for any file, especially in directories where malware was found", ifConfirmed: "Register T1070.006 timestomping finding — CONFIRMS deliberate evasion", ifAbsent: "No timestamp manipulation detected (or all files have consistent times)", evidenceType: ["disk-windows"], priority: 13 },
  { id: "af_logclear", category: "ANTI_FORENSICS", subcategory: "Log_Clearing_Detection", tool: "anti_forensics", operation: "detect_log_clearing", rationale: "A multi-year workstation with zero Security events is impossible without deliberate clearing", whatEvilLooksLike: "Zero .evtx files, Security.evtx = 0 events, Event ID 1102 (audit log cleared), large gaps in sequential record IDs", whatNormalLooksLike: "Dozens of .evtx files, continuous record IDs, years of events", hypothesisTested: "Did the attacker clear event logs to destroy evidence?", confirmationCriteria: "Absence of expected logs OR presence of EID 1102 clearing event", ifConfirmed: "Register T1070.001 finding — major anti-forensics indicator", ifAbsent: "Logs intact — proceed to parse them", evidenceType: ["disk-windows"], priority: 14 },
  // ─── USER ACTIVITY ───
  { id: "ua_recycle", category: "USER_ACTIVITY", subcategory: "Recycle_Bin_Analysis", tool: "user_activity", operation: "parse_recycle_bin", rationale: "Attackers delete tools after use — $Recycle.Bin preserves the original path + deletion time", whatEvilLooksLike: "Deleted hacking tools (mimikatz, psexec), deleted scripts, deleted from ProgramData/Temp paths", whatNormalLooksLike: "User documents, downloaded files", hypothesisTested: "Did the attacker delete tools after use?", confirmationCriteria: "Deleted item with original path matching suspicious directories found earlier", ifConfirmed: "Register finding — proves tool was used then cleaned up", ifAbsent: "No deleted attack tools in recycle bin (may have used shift+delete or sdelete)", evidenceType: ["disk-windows"], priority: 15 },
  // ─── REGISTRY SYSTEM CONFIG ───
  { id: "reg_sysconfig", category: "REGISTRY", subcategory: "System_Configuration", tool: "registry", operation: "get_system_config", rationale: "Establishes baseline: hostname, domain, timezone, last shutdown — essential context for all findings", whatEvilLooksLike: "Timezone changed (anti-forensics), unexpected domain membership, recent hostname change", whatNormalLooksLike: "Consistent hostname/domain matching the case documentation", hypothesisTested: "Is the system configuration consistent with expectations?", confirmationCriteria: "Any deviation from expected configuration (wrong timezone, unexpected domain)", ifConfirmed: "Register as anomaly — affects all timestamp interpretations", ifAbsent: "System config matches expectations", evidenceType: ["disk-windows"], priority: 16 },
  { id: "reg_usb", category: "REGISTRY", subcategory: "USB_Device_History", tool: "registry", operation: "get_usb_history", rationale: "USB history reveals data exfiltration via removable media", whatEvilLooksLike: "USB devices connected during attack timeframe, especially large-capacity devices not matching corporate inventory", whatNormalLooksLike: "Standard peripherals (mouse, keyboard), corporate-issued drives", hypothesisTested: "Was data exfiltrated via USB?", confirmationCriteria: "USB storage device connected during the identified attack window", ifConfirmed: "Register T1052.001 exfiltration over USB finding", ifAbsent: "No USB exfiltration evidence", evidenceType: ["disk-windows"], priority: 17 },
  // ─── MALWARE SCANNING ───
  { id: "mal_yara", category: "MALWARE", subcategory: "YARA_Scan", tool: "persistence", operation: "scan_yara", rationale: "YARA signature scanning identifies known malware families by byte patterns", whatEvilLooksLike: "Rule matches on executables in ProgramData, Temp, or user profiles", whatNormalLooksLike: "No matches or only informational rules", hypothesisTested: "Does the suspicious binary match known malware signatures?", confirmationCriteria: "YARA rule match on a binary from a suspicious directory", ifConfirmed: "Register finding with rule name — enables attribution to known threat group", ifAbsent: "Unknown/novel malware (not in current signatures) or no malware present", evidenceType: ["disk-windows", "disk-linux"], priority: 18 },
  // ─── SAM / ACCOUNTS ───
  { id: "reg_sam", category: "REGISTRY", subcategory: "SAM_Account_Analysis", tool: "registry", operation: "parse_sam", rationale: "SAM hive reveals all local accounts, creation times, last login, failed logins, password policy", whatEvilLooksLike: "Accounts created during attack window, admin accounts with password-never-expires, accounts with zero logins (dormant backdoor)", whatNormalLooksLike: "Standard accounts matching org directory, consistent creation dates", hypothesisTested: "Were backdoor accounts created during the intrusion?", confirmationCriteria: "Account created within the attack timeframe with suspicious attributes", ifConfirmed: "Register T1136.001 Create Account finding", ifAbsent: "No account manipulation detected", evidenceType: ["disk-windows"], priority: 19 },
  // ─── LINUX ───
  { id: "linux_auth", category: "LINUX", subcategory: "Auth_Log_Analysis", tool: "linux", operation: "parse_auth_log", rationale: "auth.log records SSH logins, sudo usage, failed attempts — the backbone of Linux IR", whatEvilLooksLike: "Brute force (many failed attempts), successful login from unexpected IP, sudo by non-admin user", whatNormalLooksLike: "Standard SSH logins from known IPs, cron-triggered su", hypothesisTested: "Was there unauthorized SSH access?", confirmationCriteria: "Successful auth from unknown IP or after brute force sequence", ifConfirmed: "Register T1110.001 (brute force) or T1078 (valid accounts)", ifAbsent: "No unauthorized Linux access", evidenceType: ["disk-linux"], priority: 5 },
  { id: "linux_cron", category: "LINUX", subcategory: "Cron_Persistence", tool: "linux", operation: "parse_cron_jobs", rationale: "Cron jobs provide persistence on Linux — attacker adds reverse shell or download scripts", whatEvilLooksLike: "Entries with wget/curl to external IPs, bash -i redirects, entries in user crontabs for non-standard tasks", whatNormalLooksLike: "System maintenance (logrotate, certbot, backups)", hypothesisTested: "Did the attacker establish cron-based persistence?", confirmationCriteria: "Cron entry with network call or shell redirect", ifConfirmed: "Register T1053.003 Cron persistence finding", ifAbsent: "No cron persistence", evidenceType: ["disk-linux"], priority: 6 },
  // ─── EXECUTION ARTIFACTS (continued) ───
  { id: "exec_prefetch", category: "EXECUTION", subcategory: "Prefetch_Parsing", tool: "execution_artifacts", operation: "parse_prefetch", rationale: "Prefetch files contain execution timestamps + loaded DLLs — proves exactly WHEN a binary ran", whatEvilLooksLike: "Recent execution of attack tools (sdelete, psexec, mimikatz) with loaded DLLs from ProgramData", whatNormalLooksLike: "Chrome, Office, Windows Update executables", hypothesisTested: "When exactly did the malware execute and what DLLs did it load?", confirmationCriteria: "Prefetch entry for any binary found in the staging directory, with last-run time in attack window", ifConfirmed: "Register finding with exact execution timestamp — anchors the attack timeline", ifAbsent: "Binary may not have been executed (staged but not run), or prefetch was disabled/cleared", evidenceType: ["disk-windows"], priority: 18 },
  // ─── EVENT LOGS (continued) ───
  { id: "evtx_accounts", category: "EVENT_LOGS", subcategory: "Account_Manipulation", tool: "event_logs", operation: "detect_account_manipulation", rationale: "EID 4720/4722/4724/4732 reveal account creation, enabling, password reset, group membership changes — core persistence indicators", whatEvilLooksLike: "New accounts created outside business hours, password resets for admin accounts, accounts added to privileged groups", whatNormalLooksLike: "Scheduled password rotations, HR-initiated account changes during business hours", hypothesisTested: "Did the attacker create or modify accounts for persistence?", confirmationCriteria: "Account changes in the attack timeframe OR targeting accounts seen in other findings", ifConfirmed: "Register T1136.001 (local account creation) or T1098 (account manipulation)", ifAbsent: "No account-based persistence detected", evidenceType: ["disk-windows"], priority: 19 },
  // ─── USER ACTIVITY (continued) ───
  { id: "ua_lnk", category: "USER_ACTIVITY", subcategory: "LNK_File_Analysis", tool: "user_activity", operation: "parse_lnk_files", rationale: "LNK files record target path + timestamps + volume serial number — prove file access even after deletion", whatEvilLooksLike: "LNK files pointing to attack tools, staging directories, or exfiltration targets", whatNormalLooksLike: "LNK files for common applications, recently opened documents", hypothesisTested: "Which files/tools did users actually open/execute?", confirmationCriteria: "LNK target path matching a known-malicious location from earlier findings", ifConfirmed: "Proves user interaction with attacker artifacts — ties a user account to the intrusion", ifAbsent: "No LNK evidence of tool execution (attacker may have cleaned LNK files)", evidenceType: ["disk-windows"], priority: 20 },
  { id: "ua_activity", category: "USER_ACTIVITY", subcategory: "User_Registry_Activity", tool: "registry", operation: "get_user_activity", rationale: "NTUSER.DAT reveals typed paths, recent documents, UserAssist — complete user behavior profile", whatEvilLooksLike: "Typed paths to attacker staging dirs, recent docs include sensitive files, UserAssist shows tool execution", whatNormalLooksLike: "Standard application usage, business documents", hypothesisTested: "What did the compromised user account actually do on this system?", confirmationCriteria: "Typed paths or recent docs pointing to directories where malware/staging was found", ifConfirmed: "Links user account behavior directly to attack activity", ifAbsent: "User profile clean — account may have been used only for automated access", evidenceType: ["disk-windows"], priority: 21 },
  // ─── ANTI-FORENSICS (continued) ───
  { id: "af_deletion", category: "ANTI_FORENSICS", subcategory: "Secure_Deletion_Detection", tool: "anti_forensics", operation: "detect_secure_deletion", rationale: "Secure deletion tools (sdelete, cipher /w) overwrite data — detectable by MFT orphan patterns", whatEvilLooksLike: "MFT entries with allocated metadata but zero data runs, files in known attack paths with wiped content", whatNormalLooksLike: "Normal deleted files have data runs pointing to clusters", hypothesisTested: "Did the attacker securely wipe files to destroy evidence?", confirmationCriteria: "Zero-byte files in attack-related directories OR sdelete prefetch entry", ifConfirmed: "Register T1070.004 — confirms deliberate evidence destruction", ifAbsent: "No secure deletion detected — evidence may be recoverable from unallocated space", evidenceType: ["disk-windows", "disk-linux"], priority: 22 },
  // ─── LINUX ───
  { id: "linux_bash", category: "LINUX", subcategory: "Bash_History", tool: "linux", operation: "parse_bash_history", rationale: "Bash history reveals exactly what commands the attacker ran — often not cleared", whatEvilLooksLike: "wget/curl to external IPs, chmod +x, cron editing, /etc/shadow access, ssh-keygen, iptables changes", whatNormalLooksLike: "Standard admin commands, package management, service restarts", hypothesisTested: "What commands did the attacker execute on this Linux host?", confirmationCriteria: "Commands downloading tools, modifying persistence, or accessing sensitive files", ifConfirmed: "Register findings for each attack technique observed in history", ifAbsent: "History may have been cleared (check .bash_history file size — 0 bytes = cleared)", evidenceType: ["disk-linux"], priority: 25 },
  { id: "linux_persistence", category: "LINUX", subcategory: "Linux_Persistence_Check", tool: "linux", operation: "check_linux_persistence", rationale: "Linux persistence via cron, systemd, init.d, bashrc, authorized_keys, LD_PRELOAD", whatEvilLooksLike: "Cron jobs downloading from external IPs, systemd services running from /tmp, authorized_keys with unknown public keys", whatNormalLooksLike: "Standard cron (logrotate, certbot), system services, admin SSH keys", hypothesisTested: "Did the attacker establish persistence on this Linux host?", confirmationCriteria: "Persistence mechanism pointing to suspicious binary or external infrastructure", ifConfirmed: "Register T1053.003 (cron) or T1543.002 (systemd) finding", ifAbsent: "No Linux persistence detected", evidenceType: ["disk-linux"], priority: 26 },
] as const;

/** Get the applicable ontology nodes for a given evidence type */
export function getApplicableNodes(evidenceType: string): readonly InvestigationNode[] {
  return INVESTIGATION_ONTOLOGY.filter(n => n.evidenceType.includes(evidenceType as never));
}

/** Get a specific node by ID */
export function getNodeById(id: string): InvestigationNode | undefined {
  return INVESTIGATION_ONTOLOGY.find(n => n.id === id);
}
